name: clang-format-linter

on:
  push:
    paths:
      - docs/**
      - i18n/**
  pull_request:
    paths:
      - docs/**
      - i18n/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: './docs ./i18n'
          extensions: 'c,cpp,h'
          clangFormatVersion: 16
